"""game table

Revision ID: 387912a057fe
Revises: 11bf8ae31a2e
Create Date: 2018-02-07 14:55:06.159642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387912a057fe'
down_revision = '11bf8ae31a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('playtime', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'playtime')
    # ### end Alembic commands ###
