"""game table

Revision ID: 74d5ad60fc4a
Revises: 51d7068fc180
Create Date: 2018-02-07 14:45:36.217556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d5ad60fc4a'
down_revision = '51d7068fc180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('players_min', sa.Integer(), nullable=True),
    sa.Column('players_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_title'), 'game', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_title'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
